FROM ubuntu:16.04

RUN apt-get update
RUN apt-get install -y python3 python3-pip
RUN apt-get install -y graphviz
RUN pip3 install --upgrade pip
RUN pip3 install numpy pandas graphviz matplotlib


WORKDIR /app

COPY . .
